### ISSUE TITLE
Support array of strings as output

### ISSUE THREAD

**Issue by rvalitov** [McCzarny/upload-image#10]
Github actions support `array` type. It would be nice to be able to have `urls` output field that is an array of strings = uploaded URLs. Such approach makes it easier to refer to specific URL by index later in workflow. Currently the `url` output field is a single string that requires preprocessing to split it into array - that makes it usable in a real life workflow. Otherwise without conversion to array first - working with `url` is troublesome.

**Comment by McCzarny** [comment]
Good to know, I will looks into it soon ;)

**Comment by rvalitov** [comment]
Thank you! It seems you only need to add a new variable here:
 https://github.com/McCzarny/upload-image/blob/49930cb706f8556a3c6c238d972a76b430d82086/uploadImgbb.js#L49

Something like:
```js
return {url: response.data.data.url, urls: response.data.data.url.split(","), expiration: response.data.data.expiration}; 
```

**Comment by rvalitov** [comment]
I can make a PR for that, if this approach is OK?

**Comment by McCzarny** [comment]
Of course, if you have a problem, you can bring it here. To run tests you need an env variable `API_KEY` with the API key for imgbb.
