### ISSUE TITLE
apiKey is required, even that it is passed in job

### ISSUE THREAD

**Issue by wkobiela** [McCzarny/upload-image#18]
```
##[debug]Evaluating condition for step: 'Upload image'
##[debug]Evaluating: (success() && (github.event_name == 'pull_request'))
##[debug]Evaluating And:
##[debug]..Evaluating success:
##[debug]..=> true
##[debug]..Evaluating Equal:
##[debug]....Evaluating Index:
##[debug]......Evaluating github:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'event_name'
##[debug]....=> 'pull_request'
##[debug]....Evaluating String:
##[debug]....=> 'pull_request'
##[debug]..=> true
##[debug]=> true
##[debug]Expanded: (true && ('pull_request' == 'pull_request'))
##[debug]Result: true
##[debug]Starting: Upload image
##[debug]Loading inputs
##[debug]Evaluating: secrets.IMGBB_API_KEY
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'IMGBB_API_KEY'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run McCzarny/upload-image@v1.[3](https://github.com/ammofinder/frontend/actions/runs/12232041175/job/34144503171#step:14:3).0
Uploding an image preview.png to imgbb...
Error: apiKey is required
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Upload image
```
job fragment:
```
    - name: Upload image
      id: upload-image-0
      uses: McCzarny/upload-image@v1.2.5
      if: github.event_name == 'pull_request'
      with:
        path: preview.png
        uploadMethod: imgbb
        apiKey: '${{ secrets.IMGBB_API_KEY }}'
```

so apiKey is passed, yet action is failing

**Comment by McCzarny** [comment]
Hello, let's start with 2 things:
1) Please move to version `v1.3.0`. The action was refreshed recently with updated dependencies, including the current github actions core. 
2) Double check that the secret is defined in the right place:
![image](https://github.com/user-attachments/assets/ce9ce4a4-5b8d-440a-b5e9-844a6cd7988c)

**Comment by wkobiela** [comment]
Job is failing on PR check, on bumping to 1.3.0
https://github.com/ammofinder/frontend/pull/29

api key is properly set up, and I just set it up again before rerunning job - still failing
![image](https://github.com/user-attachments/assets/98e28a49-7acb-4e46-938c-80d6254f1701)

**Comment by McCzarny** [comment]
This part concerns me:
```
##[debug]..Evaluating String:
##[debug]..=> 'IMGBB_API_KEY'
##[debug]=> null
##[debug]Result: null
```
It looks like the pipeline tries to evaluate the secret but `null` is returned. I will check it with debug on on my side.

**Comment by McCzarny** [comment]
Another shot - The PR comes from dependabot. There is a separate section in the secretes for it. I've never used secrets with dependabot, so I'm not sure, but maybe it only has access to secrets defined in Dependabot?
Here is the same part printed in case the action works: 

```
##[debug***..Evaluating String:
##[debug***..=> 'IMGBB_API_KEY'
##[debug***=> '***'
##[debug***Result: '***'
```

**Comment by wkobiela** [comment]
You are right - for dependabot PRs there is a need to duplicate all required keys. Just added there, and action passed.
I'm closing as resolved, thanks
